version: "3"

services:
  rtbctf:
    image: eshaan7/rtb-ctf-framework
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      - DEBUG=False
      - SSL_ENABLED=False
      - DB_USER=eshaan
      - DB_PASSWORD=eshaan
      - DB_NAME=rtbctf
      - DB_PORT=5432
      - WORKERS=4
      - ADMIN_PASS=admin
    depends_on:
      - postgres
      - redis

  postgres:
    image: library/postgres:12.1-alpine
    container_name: rtb_postgres
    restart: unless-stopped
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=eshaan
      - POSTGRES_PASSWORD=eshaan
      - POSTGRES_DB=rtbctf

  redis:
    image: redis:6.0-rc4-alpine
    container_name: rtb_redis
    restart: unless-stopped
    expose:
      - "6379"

  
  nginx:
    image: library/nginx:1.16.1-alpine
    container_name: rtb_nginx
    restart: unless-stopped
    hostname: nginx
    volumes:
      - ./rtb_nginx_http:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - rtbctf
